### ISSUE TITLE
can props be passed down to a node from markup?

### ISSUE THREAD

**Issue by soenkekluth** [developit/preact-markup#12]
for example: i want to pass down a function / method that should be called, when the element is clicked.

and one more thing.
this is content of the markup:
`<button type="button" onClick={console.log(this)}>click me</button>`

why do i get
`Object {click: function}click: function anonymous()...`
tracing out 'this'

**Comment by developit** [comment]
@soenkekluth Can't do that since it's HTML, not JSX, so the values are inert Strings.

The closest you could get would be to inject a parsing middleware into Preact that detects String values for `on*` attributes and turns them into functions:

```js
import { options } from 'preact';

let old = options.vnode;
options.vnode = vnode => {
  let props = vnode.attributes;
  if (props) for (let i in props) {
    if (typeof props[i]==='string' && i.match(/^on\w+$/i)) {
      props[i] = new Function(props[i]);
    }
  }
  if (old) old(vnode);
};
```

**Comment by soenkekluth** [comment]
perfect thanks.
