### ISSUE TITLE
JSFiddle Demo Fails To Render

### ISSUE THREAD

**Issue by zouhir** [developit/preact-markup#13]
I just noticed that JS Fiddle demo uses latest Preact where `linkState` has been moved to it's standalone module. all we need is to `import linkState` and replace all `this.linkState`

I can fork the JSFiddle but I can't update @developit original one.

any suggestions how can I help?

**Comment by developit** [comment]
Fixed!

**Comment by developit** [comment]
For the fiddles and stuff they're all hopelessly tied to my account (annoying), not sure of a way around that. Github-based examples are better in that regard I guess.

**Comment by zouhir** [comment]
@developit we probably can make them examples inside each repo - people examples folder inside repos.

**Comment by developit** [comment]
yup, just makes hosting a little more annoying (gh pages), but I'm down. I usually end up with jsfiddle/codepen because it's so quick for me to create them.
