### ISSUE TITLE
Preact X import issue

### ISSUE THREAD

**Issue by Friph** [developit/preact-markup#27]
Hey,

when I import preact-markup in Preact X I got this error: 

![image](https://user-images.githubusercontent.com/31510303/60789308-18b52300-a15f-11e9-89cc-b86508fb6d15.png)

Anyone could help?

**Comment by NicolaiSchmid** [comment]
What error? You didn't post any logs

**Comment by developit** [comment]
Please use the new 2.0.0 version with Preact X, just released:

```
npm install --save preact-markup@next
```
