### ISSUE TITLE
<img alt="true" /> being set when alt="" is provided

### ISSUE THREAD

**Issue by donovantc** [developit/preact-markup#32]
Hi,

when setting `alt=""` inside of `<img />` html elements in an `.ejs` template, the `alt` attribute is modified to `alt="true"` when rendered with the `<Markup />` component.

Is this intentional and if yes, is there a way to disable this?

Thanks in advance.

**Comment by meengit** [comment]
Hi,

I have a similar issue in using with form input fields.

### Axios response (simplified)

Just before `preact-markup`:

```html
<label>E-Mail</label>
<input value="" placeholder="E-Mail *" />
```

### Preact makrup

```jsx
<Markup markup={html} trim={false} type="html" />
```
### "In DOM" (simplified)

```html
<label>E-Mail</label>
<input placeholder="E-Mail">
```
### Displayed as

![form](https://user-images.githubusercontent.com/6507355/67289408-dda4e880-f4de-11e9-8316-3c3080baff49.png)

### Question

I am not entirely sure if it is really a problem related to `preact-markup`. I noticed that the attribute `value` is present before `Markup` however, not afterward. Some advice would be helpful @developit.

**Comment by vpzomtrrfrt** [comment]
I suspect it's this line?
https://github.com/developit/preact-markup/blob/master/src/to-vdom.js#L55

**Comment by developit** [comment]
Ah yes @vpzomtrrfrt - that line should be removed. Preact X corrected Boolean attribute behaviour and we no longer need that workaround.
