### ISSUE TITLE
Hydration of bad html breaking render :(

### ISSUE THREAD

**Issue by guaiamum** [developit/preact-markup#33]
Hey! So...

I don't know if I can link an example to demonstrate what's happening, but I'll try my best to explain it...

Using this component in **SSR** with the linked markup renders an invalid html and does not call the _onError_ method (Is this correct?), but the node jsdom parser parses anyway and no errors are thrown.

On the client side, when the hydration process is running, the following Error is thrown and the page crashes entirely `Uncaught (in promise) DOMException: Failed to execute 'setAttribute' on 'Element': 'sans",' is not a valid attribute name.`.

I'm guessing the Error is in the hydration phase, because I tried **SSR**'ing the markup with the component, and **CSR**'ing it with _setDangerously_ and the page won't crash, and the invalid HTML stays there in the DOM, quietly broken...

The problematic markup: `<div style="font-family:"sans""></div>`

Could someone please help me find a way to use the component but avoid the page breaking? Thanks!

**Comment by yunyu** [comment]
This library just doesn't seem to work in a Node.js environment in general. Using preact-render-to-string on this just returns `<undefined></undefined>`.

**Comment by guaiamum** [comment]
> This library just doesn't seem to work in a Node.js environment in general. Using preact-render-to-string on this just returns `<undefined></undefined>`.

What version did you use for each? I raised the issue quite a while ago, before preact X anyway...

**Comment by yunyu** [comment]
I am using Preact X and Preact Markup 2.0.0, so I can confirm this is still a problem with the latest versions of everything.

**Comment by yunyu** [comment]
I tried injecting `global.DOMParser` with [xmldom](https://www.npmjs.com/package/xmldom), and tracing through the code it looks like some VNodes are being spit out correctly, but preact-render-to-string still returns `<undefined></undefined>`.

**Comment by guaiamum** [comment]
Nice, what about the problematic markup? Does it get spitted correctly? If so, I think we can close the issue :)

**Comment by developit** [comment]
Hiya! This library doesn't make invalid HTML work with VDOM - it uses the browser's HTML parser, which is more tolerant than JSX/VDOM. The `<div style="font-family:"sans""></div>` example parses to this:

```js
<div style="font-family:" sans""={true} />
```

... which fails because attribute names cannot contain a quote character. It works during SSR because `render-to-string` does not validate attribute names at all.
