### ISSUE TITLE
Wont render when there is an & symbol in a string

### ISSUE THREAD

**Issue by drastick** [developit/preact-markup#4]
https://jsfiddle.net/dddat8Lx/1/

**Comment by developit** [comment]
Ah - looks like this is sortof a documentation issue:  by default, `preact-markup` uses an XML parser, which cannot render `&` as a textual character (it must be encoded as `&amp;`).  For the fiddle, either tell `preact-markup` parse as HTML (`type="html"`), or encode the entity:
https://jsfiddle.net/developit/dddat8Lx/2/

I think there is a fix here though, which is to properly document the `type` prop, and also pipe parse errors to the console.

**Comment by developit** [comment]
Released in `preact-markup@1.4.0`
