### ISSUE TITLE
preact-markup@1.6.0 incompatible with wmr

### ISSUE THREAD

**Issue by orzechowskid** [developit/preact-markup#44]
I'm attempting to move a personal project to wmr and ran into a spot of trouble with this library.  installing preact-markup@1.6.0 then running `wmr` in my project gives me an error in my browser console: `Uncaught (in promise) SyntaxError: import not found: default`.

installing preact-markup@next appears to fix the issue for me, so no worries there, but I was wondering at what point `@next` will become `@latest`; it seems like anyone who uses Preact X already needs `@next` (#27) and now I think anyone who uses wmr will want it too.  If there are good reasons not to re-tag current `next` as `latest` then I'd be happy to open a documentation PR here describing when to use what versions of this library. 

thanks for your hard work on both of these tools!

**Comment by developit** [comment]
Ah! Yeah this library should definitely be cut over to version 2 being the default. I will do that ASAP.

**Comment by developit** [comment]
Alrighty, I published 2.1.0 as `@latest`. Thanks for the reminder!
